name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  firebase_core: ^3.5.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4
  image_picker: ^1.0.0
  http: ^1.0.0
  google_sign_in: ^6.2.1
  lucide_icons: ^0.257.0
  pdf: ^3.10.7
  printing: ^5.13.1
  lucide_icons_flutter: ^3.1.5
  intl: ^0.19.0
  fl_chart: ^0.68.0
  cloudinary_public: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: 0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/burger_bg.jpg
    - assets/google.png
    - assets/qr-code.jpg

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon.png"
